# Generated by Django 6.0.3 on 2026-04-03 13:20

import django.db.models.deletion
from django.db import migrations, models

def copy_author_str(apps, schema_editor):
    Book = apps.get_model('store', 'Book')
    for book in Book.objects.all():
        book.author_str = book.author
        book.save()
    Book.objects.all().update(author=None)

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_author_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_str',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RunPython(copy_author_str, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.author'),
        ),
    ]
