# Generated by Django 6.0.3 on 2026-04-03 13:41

from django.db import migrations


def populate_authors(apps, schema_editor):
    Book = apps.get_model('store', 'Book')
    Author = apps.get_model('store', 'Author')
    for book in Book.objects.exclude(author_str=None):
        parts = book.author_str.strip().rsplit(' ', 1)
        if len(parts) == 2:
            first_name, last_name = parts
        else:
            first_name, last_name = '', parts[0]
        author, _ = Author.objects.get_or_create(
            first_name=first_name,
            last_name=last_name,
        )
        book.author = author
        book.save()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_author_str_alter_book_author'),
    ]

    operations = [
        migrations.RunPython(populate_authors, migrations.RunPython.noop),
    ]

