# Generated by Django 6.0.3 on 2026-04-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_str',
        ),
    ]
