# Generated by Django 6.0.3 on 2026-04-07 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_book_author_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curator', models.CharField(max_length=80)),
                ('established', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='library',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.library'),
        ),
    ]
