# Generated by Django 6.0.3 on 2026-04-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_library_author_library'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Museum'},
        ),
    ]
