# Generated by Django 6.0.3 on 2026-04-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_library_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('iso', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.ManyToManyField(to='store.country'),
        ),
    ]
