# Generated by Django 6.0.3 on 2026-04-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_country_book_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
