# Generated by Django 6.0.3 on 2026-05-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('review_text', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
